import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import Navbar from "@/components/Navbar";
import SessionWrapper from "./providers/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SessionWrapper>
        <div>
        {/* <VerificationEmail/> */}
        </div>
        <div>
          <Navbar/>
          <ToastContainer position="bottom-right" theme="dark" />
        {children}
        </div>
        </SessionWrapper>
      </body>
    </html>
  );
}
